### ISSUE TITLE
有关数据集标注的困惑

### ISSUE THREAD

**Issue by panruotong** [THU-KEG/CCL2022_Storyline_Relationship_Classification#3]
尊敬的老师，您好，有关数据集标注有一些疑问想请教。在训练集第11行和第14行，同为地方政府召开主题为碳达峰、碳中和的会议，商讨有关措施，为什么两个文档标签不同？
比较文档：环资司参加“碳路中国”绿色发展大会。5月15日，中科院生态环境研究中心、山东省发展改革委和潍坊市人民政府共同举办碳路中国绿色发展大会，大会主题是绿色能源与循环经济下的机遇与挑战。国家发展改革委环资司二级巡视员杨尚宝受邀出席并致辞，强调碳达峰、碳中和是以习近平同志为核心的党中央经过深思熟虑作出的重大战略决策，介绍了国家发展改革委正在推进的有关工作，希望潍坊市坚定不移贯彻新发展理念，走生态优先、绿色低碳的高质量发展道路。大会举办了项目集中签约、产业研究院揭牌等活动，发布了碳路中国绿色发展大会宣言。

第11行：科技创新助力成都实现“碳达峰”“碳中和”。近年来，成都全市碳排放强度进一步降低，能源结构不断优化，城市环境更加宜居。图为交子公园本报资料图片碳达峰指全球、国家、城市、企业等主体的碳排放在由升转降的过程中，碳排放的最高点即碳峰值碳中和指人为排放源与通过植树造林、碳捕集与封存技术等人为吸收汇达到平衡努力建设碳中和先锋城市，成都有哪些优势？如何激励企业在零碳创新上发挥更多的创造力？依托公园城市底色，双碳目标下一步落子何在？强化科技创新支撑，成都已快速行动起来。5月19日，科技支撑成都碳达峰、碳中和专家研讨会在成都举行。围绕政策措施、技术路线、技术趋势以及企业技术需求等议题，来自川内外的专家学者、企业代表展开了讨论。【优势】可再生资源基础雄厚绿色低碳特质鲜明3月15日召开的中央财经委员会第九次会议指出，实现碳达峰碳中和是一场广泛而深刻的经济社会系统性变革，面对这场硬仗，作为国家批准的低碳试点城市之一，成都早已展开布局。目前成都90%的电力都已使用可再生资源，具有良好的基础与优势。接下来，可关注跨行业的工业流程再造，并做出成都特色。四川省碳中和技术创新中心常务副主任、四川大学建筑与环境学院教授江霞认为，在碳达峰碳中和目标下，成都可以对重点产业、能源消耗结构做一个系统画像，并对标国内外城市，制定成都科技行动方案。同时，还应该制定任务清单，明确路线图施工图。实现碳达峰碳中和，成都从全国来说都具有独一无二的优势。在中国绿色发展协同创新中心执行主任、研究员张九天看来，成都是成渝地区双城经济圈建设中的重要一极，在国家布局中具有重要地位；同时，西南地区能源资源丰富，成都具备较好的能源结构；在科技创新基础上，成都高校院所林立，创新资源集中。在低碳城市建设636工程有力实施下，近年来，成都全市碳排放强度进一步降低，能源结构不断优化，城市环境更加宜居，人均碳排放位列北上广深等全国十大城市最低，荣获首批全球绿色低碳领域先锋城市蓝天奖。绿色低碳，正逐步成为成都最鲜明的特质和优势。关键是要把成都的优势转化为竞争力，实现绿色低碳高质量发展。张九天认为，这就需要跳出成都看成都，在产业发展方面，既要从国家政策方面全盘规划产业发展方向，也要从产业链的角度攻破关键节点；在技术创新方面，要接轨世界科技前沿创新和产业变革趋势，挖掘科技潜力，利用好科教资源，让绿色低碳的技术在成都落地、生根、发芽。【探索】强化科技创新支撑成都科技企业抢先布局今年3月，市政府印发了《关于构建碳惠天府机制的实施意见》，打造绿色低碳城市正在进行时，成都蓝越来越成为常态。记者了解到，随着碳达峰碳中和火热出圈，成都科技企业也已加快布局，为实现双碳目标提供强有力的技术支撑。通威集团是全行业首家提出碳中和目标的民营企业。通过推动全厂数字化建设，化石能源逐步替代等方式，通威集团已提前规划、布局，并正在积极起草、推动行业相关标准建立。通威永祥股份有限公司相关负责人表示。东方电气集团中央研究院战略和技术研究所研究员郑玉恒介绍，目前，东方电气在氢能全产业链的设备技术都较为完善，包括制氢、储氢、运氢，还有燃料电池、膜电极、电池组等，我们研发生产的燃料电池大巴在成都也运行了很久，下一步我们将继续围绕PEM技术的成本和材料寿命两方面进行科研攻关。据中自环保科技股份有限公司董事长陈启章介绍，依托四川省天然气基础以及四川大学研发实力，该企业以催化剂技术为核心，致力于研发天然气、柴油、汽油等燃料发动机排放后处理催化剂，以及氢燃料电池催化剂。产学研用相结合为企业提供补齐、整合产业链的技术支持，希望未来涌现更多的新能源应用场景，为本地产业率先提供应用支持。【目标】努力建设碳中和先锋城市迈向多元化清洁能源共存时代努力建设碳中和先锋城市，成都正依托科技支撑，着手打头阵，计划编制碳达峰行动方案，积极组建碳中和实验室，构建碳中和产业生态圈，提升城市能级与竞争力。一如既往地为广大企业提供最优质、最高效、最便捷的服务保障，让大家在成都放心投资、安心发展、舒心生活，携手共建共享新时代雪山下的公园城市。加大光电水电风电及其他清洁环保能源的建设和生产、开发是城市发展全盘棋中的关键之举。在四川大学建筑与环境学院教授楚英豪看来，在应用层面成都需要摸清家底，运用好现阶段的减碳技术，率先尝试高碳产品向低碳产品转型，探索新路径；在科学技术方面，梳理现阶段高耗能企业转型难点，通过科技立项协助企业转型。聚焦成都碳达峰、碳中和目标，我们作为能源领域的研究机构，可以从能源的供给侧以及能源消费侧两个方面来开展工作。在清华四川能源互联网研究院高级工程师程青看来，四川具有良好的水电优势，能源清洁化比例较高，但是大规模高比例可再生能源接入对能源系统的稳定性安全性来说有非常大的挑战。如何来应对挑战？加速升级和改造高比例可再生能源接入的新型电力系统是接下来探索的方向。独家对话清华大学环境学院教授王灿：城市化带来的碳增加将随着科学技术的发展和产业结构调整而逐步抵消自提出双碳工作以来，成都强调碳综合产业，在工业领域考虑产业布局调整。作为高校的西部聚集区，研发基础良好，研发平台多，科技支撑能力强，对交通统筹协调力度大。但与此同时，城市化率提高，需要为新增城市人口提供住房，对交通运输、医疗卫生、城市绿化等公共基础设施都提出更高要求，因而对能源的需求将大大增加。清华大学环境学院教授王灿阐述了对成都双碳工作高定位的理解，从整体看，成都走在了全国前列。目前，双碳工作一直强调低碳，哪种程度才算低？王灿表示，零排放是未来必然之举。碳排放主要有5大来源，包括工业40亿吨，电力40亿吨，交通、建筑共20亿吨，非二氧化碳30亿到40亿吨，这些领域都是需要减排的对象。王灿认为，可通过探索4大技术路径实现碳零排放，首先需要电气化100%普及，在电气不能满足需求的领域大力发展新能源。双碳工作分为近期的碳达峰目标和远期的碳中和目标，从长远看，城市化带来的碳排放增加等问题也将随着科学技术的发展和产业结构调整而逐步抵消。这是任重道远的工作，需要所有人共同努力。本报记者曹凘源实习记者李菲菲原标题：科技创新助力成都实现碳达峰碳中和

第14行：天津市“碳达峰、碳中和”产业联盟揭牌。中新网天津5月21日电以智慧能源助力碳达峰、碳中和为主题的第五届世界智能大会城市能源革命高峰论坛20日启幕。天津市碳达峰、碳中和产业联盟在论坛上正式揭牌。本次高峰论坛由国家能源局、中国电机工程学会指导，国家电网公司主办，天津市工业和信息化局、天津市发展和改革委员会、国网天津市电力公司承办，是加快双碳目标落地的具体行动。论坛上，中国工程院院士余贻鑫、郭剑波等围绕双碳目标-智能电网-新兴产业双碳目标下电力系统发展及挑战等作主旨演讲。加拿大工程院院士、清华大学专家学者，以及华为公司、芬兰能源企业代表分别以现场演讲和云端连线方式，围绕智慧能源、新型电力系统构建等内容，开展深入研讨和交流，推动转变传统电网理念，广泛凝聚智慧能源发展共识、促进交流与合作，进一步引领城市智慧能源发展，助力碳达峰、碳中和目标实现。国网天津市电力公司发布全国首个政企合作能源电力碳达峰、碳中和先行示范区实施方案。加快智能电网新技术和商业模式探索，为碳达峰、碳中和贡献中国方案中国力量。同时，天津市碳达峰、碳中和产业联盟在本次高峰论坛上正式揭牌。联盟由能源电力相关行业协会、电网企业、发电企业、能源设备生产企业、大型用能企业、科研院校、设计院等组成，以提升天津市能源电力产业在国内外市场整体竞争力为目标，依据联盟章程，协调能源企业、科研院校和设计院实现真正的技术融合，有效提高联盟成员在技术研发、市场开拓、配套供给等过程中的效率，推动形成共建、共治、共享产业生态圈。

**Comment by Anifled** [comment]
你好，感谢你的提问。这个应该训练集标注有误。标签应该是都为1的。

**Comment by panruotong** [comment]
谢谢您的回复
