### ISSUE TITLE
最后两天成绩更新以及最终结果提交

### ISSUE THREAD

**Issue by bigstrawberrywakaka** [THU-KEG/CCL2022_Storyline_Relationship_Classification#6]
老师：
您好，邮件提到最终排名是最终提交的代码文档对应的结果文件，那可以把之前提交的结果成绩给我们一下么，中途提交过的结果都只有最高成绩和最新成绩，还有老师可以今明最后两天再更新一下么，明天不更新的话就是四天没更新了，直接用最后一次提交的结果，按照直觉交一个方法，比赛有点像摸奖了，谢谢老师！

**Comment by hlee-top** [comment]
这样对每次更新只提交一两次的队伍不太公平吧

**Comment by bigstrawberrywakaka** [comment]
> 这样对每次更新只提交一两次的队伍不太公平吧

规则写了的可以多次提交，按照规则提交有啥不公平的...

**Comment by xiamaozi11** [comment]
最好能给个最好提交结果吧

**Comment by bigstrawberrywakaka** [comment]
谢谢老师！！！太感动了

**Comment by bigstrawberrywakaka** [comment]
谢谢老师！！！太感动了
